# Generated by Django 5.0.4 on 2024-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_order_city_remove_order_payment_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
