# Generated by Django 5.0.4 on 2024-04-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_userprofile_is_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
